/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AM2320 */

#ifndef _Included_AM2320
#define _Included_AM2320
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     AM2320
 * Method:    getTemperature
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_AM2320_getTemperature
  (JNIEnv *, jobject);

/*
 * Class:     AM2320
 * Method:    getHumidity
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_AM2320_getHumidity
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
